# Generated by Django 2.2.1 on 2021-06-21 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('inv_number', models.CharField(blank=True, max_length=100)),
                ('factory_number', models.CharField(blank=True, max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('origin_factory', models.CharField(blank=True, max_length=100)),
                ('origin_year', models.CharField(blank=True, max_length=100)),
                ('used_year', models.CharField(blank=True, max_length=100)),
                ('battery', models.BooleanField(default=False)),
                ('status_battery', models.IntegerField(default=0)),
                ('status_passport', models.IntegerField(default=0)),
                ('passport', models.FileField(blank=True, upload_to='index/static/files/')),
                ('compatibility_file', models.FileField(blank=True, upload_to='index/static/files/')),
                ('status_compatibility_file_value', models.IntegerField(default=0)),
                ('responsible_user', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Appliances',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tel_number', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ResponsiblePersons',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Company')),
                ('permission', models.BooleanField(default=False)),
                ('admin_type', models.IntegerField(choices=[(0, 'user'), (1, 'admin')], default=0)),
                ('user', models.OneToOneField(help_text='User linked to this profile', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Related user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('invalid_file', models.FileField(blank=True, upload_to='index/static/files/')),
                ('status', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('appliance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='index.Appliance')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('responsible_department', models.CharField(blank=True, max_length=100)),
                ('checked_organization', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, default=False, upload_to='index/static/files/')),
                ('status', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='index.Appliance')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='appliance',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='index.Category'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='exploit_department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='index.Departments'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='index.Subcategory'),
        ),
    ]
