# Generated by Django 2.2.1 on 2021-06-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='exploit_department',
            new_name='department',
        ),
    ]
