# Generated by Django 2.2.1 on 2021-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210630_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True),
        ),
    ]
