# Generated by Django 2.2.1 on 2021-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210716_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='origin_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='used_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
