# Generated by Django 2.2.1 on 2021-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210724_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='compatibility_file',
            field=models.FileField(blank=True, upload_to='index/data/files/'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='passport',
            field=models.FileField(blank=True, upload_to='index/data/files/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='invalid_file',
            field=models.FileField(blank=True, upload_to='index/data/files/'),
        ),
    ]
