# Generated by Django 2.2.1 on 2021-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210802_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='last',
            field=models.IntegerField(default=0),
        ),
    ]
