# Generated by Django 2.2.1 on 2021-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_certificate_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
