# Generated by Django 2.2.1 on 2021-10-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20211018_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Certificates'},
        ),
    ]
