# Generated by Django 2.2.1 on 2021-10-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20211018_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-last'], 'verbose_name_plural': 'Certificates'},
        ),
    ]
