# Generated by Django 2.2.1 on 2021-10-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20211018_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Certificates'},
        ),
    ]
